-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 10:17:32 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema usuarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usuarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usuarios` DEFAULT CHARACTER SET utf8 ;
USE `usuarios` ;

-- -----------------------------------------------------
-- Table `usuarios`.`Contrasenas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`Contrasenas` (
  `id_contrasena` INT NOT NULL AUTO_INCREMENT,
  `contrasena` VARCHAR(150) NULL,
  `fecha_modificacion` DATETIME NULL,
  PRIMARY KEY (`id_contrasena`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`Usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `nombre_usu` VARCHAR(45) NULL,
  `apellido_usu` VARCHAR(45) NULL,
  `fecha_nac_usu` DATE NULL,
  `n_telefono_usu` VARCHAR(15) NULL,
  `email` VARCHAR(50) NULL,
  `id_contrasena_usu` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_Usuarios_Contraseñas_idx` (`id_contrasena_usu` ASC),
  CONSTRAINT `fk_Usuarios_Contraseñas`
    FOREIGN KEY (`id_contrasena_usu`)
    REFERENCES `usuarios`.`Contrasenas` (`id_contrasena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`deportes_sel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`deportes_sel` (
  `id_usuario_dep` INT NOT NULL,
  `futbol_dep` TINYINT NULL,
  `baloncesto_dep` TINYINT NULL,
  `futbol_sala` TINYINT NULL,
  `balonmano_dep` TINYINT NULL,
  INDEX `fk_deportes_sel_Usuarios1_idx` (`id_usuario_dep` ASC),
  CONSTRAINT `fk_deportes_sel_Usuarios1`
    FOREIGN KEY (`id_usuario_dep`)
    REFERENCES `usuarios`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`Metodo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`Metodo_pago` (
  `id_usuario_emt` INT NOT NULL,
  `tarjeta_met` VARCHAR(16) NOT NULL,
  `cvv_met` INT(4) NULL,
  `fecha_caducidad_met` DATE NULL,
  PRIMARY KEY (`tarjeta_met`),
  INDEX `fk_Metodo_pago_Usuarios1_idx` (`id_usuario_emt` ASC),
  CONSTRAINT `fk_Metodo_pago_Usuarios1`
    FOREIGN KEY (`id_usuario_emt`)
    REFERENCES `usuarios`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`Transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`Transacciones` (
  `id_usuario_transaccion` INT NOT NULL,
  `id_transaccion` INT NOT NULL AUTO_INCREMENT,
  `importe_transaccion` FLOAT NULL,
  `realizadas` TINYINT NULL,
  `fecha_transaccion` DATETIME NULL,
  PRIMARY KEY (`id_transaccion`),
  INDEX `fk_Transacciones_Usuarios1_idx` (`id_usuario_transaccion` ASC),
  CONSTRAINT `fk_Transacciones_Usuarios1`
    FOREIGN KEY (`id_usuario_transaccion`)
    REFERENCES `usuarios`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`tipo_conexion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`tipo_conexion` (
  `idtcon` INT NOT NULL AUTO_INCREMENT,
  `nombre_tcon` VARCHAR(45) NULL,
  PRIMARY KEY (`idtcon`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`conexiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`conexiones` (
  `idconexiones` INT NOT NULL AUTO_INCREMENT,
  `fecha_con` DATETIME NULL,
  `usuarios_con` INT NOT NULL,
  `tipo_idtcon` INT NOT NULL,
  PRIMARY KEY (`idconexiones`),
  INDEX `fk_conexiones_Usuarios1_idx` (`usuarios_con` ASC),
  INDEX `fk_conexiones_tipo_conexion1_idx` (`tipo_idtcon` ASC),
  CONSTRAINT `fk_conexiones_Usuarios1`
    FOREIGN KEY (`usuarios_con`)
    REFERENCES `usuarios`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conexiones_tipo_conexion1`
    FOREIGN KEY (`tipo_idtcon`)
    REFERENCES `usuarios`.`tipo_conexion` (`idtcon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
