-- MySQL Script generated by MySQL Workbench
-- Fri Nov 22 11:25:02 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`Deporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Deporte` (
  `iddeporte` INT NOT NULL AUTO_INCREMENT,
  `nombre_deporte` VARCHAR(45) NULL,
  PRIMARY KEY (`iddeporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`posicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`posicion` (
  `idposicion` INT NOT NULL AUTO_INCREMENT,
  `iddeporte_pos` INT NOT NULL,
  `nombre_pos` VARCHAR(45) NULL,
  PRIMARY KEY (`idposicion`, `iddeporte_pos`),
  INDEX `fk_posiciones_Deporte1_idx` (`iddeporte_pos` ASC),
  CONSTRAINT `fk_posiciones_Deporte1`
    FOREIGN KEY (`iddeporte_pos`)
    REFERENCES `proyecto`.`Deporte` (`iddeporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Estadio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Estadio` (
  `idestadio` INT NOT NULL AUTO_INCREMENT,
  `nombre_estadio` VARCHAR(45) NULL,
  PRIMARY KEY (`idestadio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Temporada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Temporada` (
  `idtemporada` INT NOT NULL AUTO_INCREMENT,
  `ano_principio` YEAR NULL,
  `ano_fin` YEAR NULL,
  PRIMARY KEY (`idtemporada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Tipo_Entrenador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Tipo_Entrenador` (
  `idtipoentrenador` INT NOT NULL AUTO_INCREMENT,
  `deporte_tent` INT NOT NULL,
  `nombre_tent` VARCHAR(45) NULL,
  PRIMARY KEY (`idtipoentrenador`, `deporte_tent`),
  INDEX `fk_Tipo_Entrenador_Deporte1_idx` (`deporte_tent` ASC),
  CONSTRAINT `fk_Tipo_Entrenador_Deporte1`
    FOREIGN KEY (`deporte_tent`)
    REFERENCES `proyecto`.`Deporte` (`iddeporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Entrenadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Entrenadores` (
  `identrenador` INT NOT NULL AUTO_INCREMENT,
  `idtemporada_ent` INT NOT NULL,
  `idtentrenador_ent` INT NOT NULL,
  `nombre_ent` VARCHAR(45) NULL,
  `apellidos_ent` VARCHAR(45) NULL,
  `nacionalidad_ent` VARCHAR(30) NULL,
  PRIMARY KEY (`identrenador`, `idtemporada_ent`),
  INDEX `fk_Entrenadores_Tipo_Entrenador_idx` (`idtentrenador_ent` ASC),
  INDEX `fk_Entrenadores_Temporada1_idx` (`idtemporada_ent` ASC),
  CONSTRAINT `fk_Entrenadores_Tipo_Entrenador`
    FOREIGN KEY (`idtentrenador_ent`)
    REFERENCES `proyecto`.`Tipo_Entrenador` (`idtipoentrenador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrenadores_Temporada1`
    FOREIGN KEY (`idtemporada_ent`)
    REFERENCES `proyecto`.`Temporada` (`idtemporada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Equipo` (
  `idequipo` INT NOT NULL AUTO_INCREMENT,
  `idtemp_eq` INT NOT NULL,
  `idestadio_eq` INT NOT NULL,
  `deporte_iddeporte` INT NOT NULL,
  `identrenador_eq` INT NOT NULL,
  `nombre_eq` VARCHAR(45) NULL,
  `ciudad_eq` VARCHAR(45) NULL,
  `provincia_eq` VARCHAR(45) NULL,
  `presidente_eq` VARCHAR(45) NULL,
  `liga_eq` VARCHAR(45) NULL,
  `division_eq` VARCHAR(45) NULL,
  PRIMARY KEY (`idequipo`, `idtemp_eq`),
  INDEX `fk_Equipos_Estadios1_idx` (`idestadio_eq` ASC),
  INDEX `fk_Equipos_Deporte1_idx` (`deporte_iddeporte` ASC),
  INDEX `fk_Equipos_Temporada1_idx` (`idtemp_eq` ASC),
  INDEX `fk_Equipos_Entrenadores1_idx` (`identrenador_eq` ASC),
  CONSTRAINT `fk_Equipos_Estadios1`
    FOREIGN KEY (`idestadio_eq`)
    REFERENCES `proyecto`.`Estadio` (`idestadio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipos_Deporte1`
    FOREIGN KEY (`deporte_iddeporte`)
    REFERENCES `proyecto`.`Deporte` (`iddeporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipos_Temporada1`
    FOREIGN KEY (`idtemp_eq`)
    REFERENCES `proyecto`.`Temporada` (`idtemporada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipos_Entrenadores1`
    FOREIGN KEY (`identrenador_eq`)
    REFERENCES `proyecto`.`Entrenadores` (`identrenador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Jugador` (
  `idjugador` INT NOT NULL AUTO_INCREMENT,
  `idtemporada_jug` INT NOT NULL,
  `idposicion_jug` INT NOT NULL,
  `equipos_jug` INT NOT NULL,
  `nombre_jug` VARCHAR(45) NULL,
  `apellido_jug` VARCHAR(45) NULL,
  `alias_jug` VARCHAR(22) NULL,
  `fechanac_jug` DATE NULL,
  `dni_jug` VARCHAR(10) NULL,
  `nacionalidad_jug` VARCHAR(30) NULL,
  `numero_jug` INT NULL,
  PRIMARY KEY (`idjugador`, `idtemporada_jug`),
  INDEX `fk_Jugadores_posiciones1_idx` (`idposicion_jug` ASC),
  INDEX `fk_Jugadores_Equipos1_idx` (`equipos_jug` ASC),
  INDEX `fk_Jugadores_Temporada1_idx` (`idtemporada_jug` ASC),
  CONSTRAINT `fk_Jugadores_posiciones1`
    FOREIGN KEY (`idposicion_jug`)
    REFERENCES `proyecto`.`posicion` (`idposicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jugadores_Equipos1`
    FOREIGN KEY (`equipos_jug`)
    REFERENCES `proyecto`.`Equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jugadores_Temporada1`
    FOREIGN KEY (`idtemporada_jug`)
    REFERENCES `proyecto`.`Temporada` (`idtemporada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Calendario` (
  `idpartido` INT NOT NULL AUTO_INCREMENT,
  `fecha_cal` DATE NOT NULL,
  `local_cal` INT NOT NULL,
  `visitante_cal` INT NOT NULL,
  `jornada_cal` VARCHAR(4) NULL,
  `idestadio_cal` INT NOT NULL,
  `temporada_cal` INT NOT NULL,
  `goleslocal_cal` INT NULL DEFAULT 0,
  `golesvisitante_cal` INT NULL DEFAULT 0,
  PRIMARY KEY (`idpartido`, `fecha_cal`),
  INDEX `fk_Partidos_Equipos1_idx` (`local_cal` ASC),
  INDEX `fk_Partidos_Equipos2_idx` (`visitante_cal` ASC),
  INDEX `fk_Partidos_Estadios1_idx` (`idestadio_cal` ASC),
  INDEX `fk_Calendario_Temporada1_idx` (`temporada_cal` ASC),
  CONSTRAINT `fk_Partidos_Equipos1`
    FOREIGN KEY (`local_cal`)
    REFERENCES `proyecto`.`Equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partidos_Equipos2`
    FOREIGN KEY (`visitante_cal`)
    REFERENCES `proyecto`.`Equipo` (`idequipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partidos_Estadios1`
    FOREIGN KEY (`idestadio_cal`)
    REFERENCES `proyecto`.`Estadio` (`idestadio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calendario_Temporada1`
    FOREIGN KEY (`temporada_cal`)
    REFERENCES `proyecto`.`Temporada` (`idtemporada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Tipo_arbitro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Tipo_arbitro` (
  `idtarbitro` INT NOT NULL AUTO_INCREMENT,
  `iddeporte_tarb` INT NOT NULL,
  `nombre_tarb` VARCHAR(45) NULL,
  PRIMARY KEY (`idtarbitro`, `iddeporte_tarb`),
  INDEX `fk_Tipo_arbitro_Deporte1_idx` (`iddeporte_tarb` ASC),
  CONSTRAINT `fk_Tipo_arbitro_Deporte1`
    FOREIGN KEY (`iddeporte_tarb`)
    REFERENCES `proyecto`.`Deporte` (`iddeporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Arbitro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Arbitro` (
  `idarbitro` INT NOT NULL AUTO_INCREMENT,
  `idtemporada_arb` INT NOT NULL,
  `idtipoarbitro_arb` INT NOT NULL,
  `nombre_arb` VARCHAR(45) NULL,
  `apellidos_arb` VARCHAR(45) NULL,
  `fechanac_arb` DATE NULL,
  PRIMARY KEY (`idarbitro`, `idtemporada_arb`),
  INDEX `fk_Arbitros_Tipo_arbitro1_idx` (`idtipoarbitro_arb` ASC),
  INDEX `fk_Arbitros_Temporada1_idx` (`idtemporada_arb` ASC),
  CONSTRAINT `fk_Arbitros_Tipo_arbitro1`
    FOREIGN KEY (`idtipoarbitro_arb`)
    REFERENCES `proyecto`.`Tipo_arbitro` (`idtarbitro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Arbitros_Temporada1`
    FOREIGN KEY (`idtemporada_arb`)
    REFERENCES `proyecto`.`Temporada` (`idtemporada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Tipo_incidencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Tipo_incidencias` (
  `idtincidencias` INT NOT NULL AUTO_INCREMENT,
  `iddeporte_tinc` INT NOT NULL,
  `nombre_tinc` VARCHAR(45) NULL,
  PRIMARY KEY (`idtincidencias`, `iddeporte_tinc`),
  INDEX `fk_Tipo_incidencias_Deporte1_idx` (`iddeporte_tinc` ASC),
  CONSTRAINT `fk_Tipo_incidencias_Deporte1`
    FOREIGN KEY (`iddeporte_tinc`)
    REFERENCES `proyecto`.`Deporte` (`iddeporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Incidencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Incidencia` (
  `idincidencia` INT NOT NULL AUTO_INCREMENT,
  `idtincidencia_inc` INT NOT NULL,
  `idpartido_inc` INT NOT NULL,
  `idjugador_inc1` INT NOT NULL DEFAULT 0,
  `idjugador_inc2` INT NULL DEFAULT 0,
  `tiempo_inc` VARCHAR(45) NULL,
  PRIMARY KEY (`idincidencia`),
  INDEX `fk_Incidencias_Tipo_incidencias1_idx` (`idtincidencia_inc` ASC),
  INDEX `fk_Incidencias_Partidos1_idx` (`idpartido_inc` ASC),
  INDEX `fk_Incidencias_Jugadores1_idx` (`idjugador_inc1` ASC),
  INDEX `fk_Incidencia_Jugador1_idx` (`idjugador_inc2` ASC),
  CONSTRAINT `fk_Incidencias_Tipo_incidencias1`
    FOREIGN KEY (`idtincidencia_inc`)
    REFERENCES `proyecto`.`Tipo_incidencias` (`idtincidencias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incidencias_Partidos1`
    FOREIGN KEY (`idpartido_inc`)
    REFERENCES `proyecto`.`Calendario` (`idpartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incidencias_Jugadores1`
    FOREIGN KEY (`idjugador_inc1`)
    REFERENCES `proyecto`.`Jugador` (`idjugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Incidencia_Jugador1`
    FOREIGN KEY (`idjugador_inc2`)
    REFERENCES `proyecto`.`Jugador` (`idjugador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto`.`Arbitra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto`.`Arbitra` (
  `idpartido_arbitra` INT NOT NULL,
  `idarbitro_arbitra` INT NOT NULL,
  PRIMARY KEY (`idpartido_arbitra`, `idarbitro_arbitra`),
  INDEX `fk_Partidos_has_Arbitros_Arbitros1_idx` (`idarbitro_arbitra` ASC),
  INDEX `fk_Partidos_has_Arbitros_Partidos1_idx` (`idpartido_arbitra` ASC),
  CONSTRAINT `fk_Partidos_has_Arbitros_Partidos1`
    FOREIGN KEY (`idpartido_arbitra`)
    REFERENCES `proyecto`.`Calendario` (`idpartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partidos_has_Arbitros_Arbitros1`
    FOREIGN KEY (`idarbitro_arbitra`)
    REFERENCES `proyecto`.`Arbitro` (`idarbitro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
