-- MySQL Script generated by MySQL Workbench
-- Mon Nov 25 12:09:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema usuarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usuarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usuarios` DEFAULT CHARACTER SET utf8 ;
USE `usuarios` ;

-- -----------------------------------------------------
-- Table `usuarios`.`Contrasenas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`Contrasenas` (
  `id_contrasena` INT NOT NULL AUTO_INCREMENT,
  `contrasena` VARCHAR(150) NULL,
  `fecha_modificacion` DATETIME NULL,
  PRIMARY KEY (`id_contrasena`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`Usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `nombre_usu` VARCHAR(45) NULL,
  `apellido_usu` VARCHAR(45) NULL,
  `fecha_nac_usu` DATE NULL,
  `n_telefono_usu` VARCHAR(45) NULL,
  `id_contrasena_usu` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_Usuarios_Contraseñas_idx` (`id_contrasena_usu` ASC),
  CONSTRAINT `fk_Usuarios_Contraseñas`
    FOREIGN KEY (`id_contrasena_usu`)
    REFERENCES `usuarios`.`Contrasenas` (`id_contrasena`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`deportes_sel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`deportes_sel` (
  `id_usuario_dep` INT NOT NULL,
  `futbol_dep` TINYINT NULL,
  `baloncesto_dep` TINYINT NULL,
  `futbol_sala` TINYINT NULL,
  `balonmano_dep` TINYINT NULL,
  INDEX `fk_deportes_sel_Usuarios1_idx` (`id_usuario_dep` ASC),
  CONSTRAINT `fk_deportes_sel_Usuarios1`
    FOREIGN KEY (`id_usuario_dep`)
    REFERENCES `usuarios`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`Metodo_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`Metodo_pago` (
  `id_usuario_emt` INT NOT NULL,
  `tarjeta_met` VARCHAR(16) NOT NULL,
  `cvv_met` INT(3) NULL,
  `fecha_caducidad_met` DATE NULL,
  PRIMARY KEY (`tarjeta_met`),
  INDEX `fk_Metodo_pago_Usuarios1_idx` (`id_usuario_emt` ASC),
  CONSTRAINT `fk_Metodo_pago_Usuarios1`
    FOREIGN KEY (`id_usuario_emt`)
    REFERENCES `usuarios`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuarios`.`Transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuarios`.`Transacciones` (
  `id_usuario_transaccion` INT NOT NULL,
  `id_transaccion` INT NOT NULL AUTO_INCREMENT,
  `importe_transaccion` FLOAT NULL,
  `fecha_transaccion` DATETIME NULL,
  PRIMARY KEY (`id_transaccion`, `id_usuario_transaccion`),
  INDEX `fk_Transacciones_Usuarios1_idx` (`id_usuario_transaccion` ASC),
  CONSTRAINT `fk_Transacciones_Usuarios1`
    FOREIGN KEY (`id_usuario_transaccion`)
    REFERENCES `usuarios`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
